name: user_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_time_range: ^0.0.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get_it: ^7.6.6
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  # json_annotation: ^4.8.1
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  time_range: ^1.1.0
  vibration: ^1.8.4

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
    - assets/json/
    - assets/gif/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/font/Urbanist-Regular.ttf
        - asset: assets/font/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/font/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/font/Urbanist-Bold.ttf
          weight: 700
